#! /bin/sh
###
# chkconfig: 35 99 55
# description: Manages stat manager for tender progect
###

# Source function library.
. /etc/rc.d/init.d/functions


EXEC=/var/www/tender/protected/extensions/statmanager/stat_manager.php
PIDFILE=/var/run/stat_manager/stat_manager.pid

start()
{
        echo -n "Starting tender stat manager"
	daemon --pidfile=${PIDFILE} ${EXEC}
        echo
}

stop()
{
        echo -n "Stopping tender stat manager"
        #To run it as root:
        PID=`cat ${PIDFILE}`
        #kill ${PID}
        killproc -p ${PIDFILE} ${EXEC}
        echo
}

case "$1" in
  start)
        start
        ;;
  stop)
	stop
        ;;
 restart)
	stop
	start
	;;
  *)
        echo "Usage: service stat_manager {start|stop}"
        exit 1
esac

exit 0
